spring:
  mail:
    port: 25
    username: 18215637262@163.com
    password: NQNPKJJNNBVYDAPF
    protocol: smtp
    host: smtp.163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mail:
  port: 993
  username: 996948901@qq.com
  password: aamsidgplsnfbfhh
  protocol: imap
  host: imap.qq.com
